### ISSUE TITLE
Make the rule File Content Regex print the offending lines

### ISSUE THREAD

**Issue by acecilia** [JamitLabs/ProjLint#31]
At the moment the printed errors are not very informative, and is impossible to find the offending line. For example:
```
/../../../ExampleApp/ExampleApp/Resources/en.lproj/Localizable.strings:-1: ProjLint:  File Content Regex Violation – Content matched regex 'Regex<"\n"(?!((([A-Z][a-z ]*)" = "\3")|(L\.[a-z][a-zA-Z]+" = ".+"));)">' where it shouldn't.
```

It will be very helpful if the error shows the offending line. 

This issue seems to be also related to https://github.com/JamitLabs/ProjLint/issues/29

**Comment by Jeehut** [comment]
Thanks for reporting the issue. You're right, there are many things that can be improved within this project and this is one of those things. Feel free to post a PR with a fix.
